from typing import Protocol, Optional, Any

class IConfigService(Protocol):
    """設定サービスのインターフェース"""
    
    def get_config(self, section: Optional[str] = None, key: Optional[str] = None) -> Any: ...
    def set_config(self, section: str, key: str, value: Any) -> None: ...
    def apply_config(self) -> None: ... 