from typing import Protocol

class IEditorService(Protocol):
    """エディタサービスのインターフェース"""
    
    def handle_key(self, raw_code: int) -> None: ...
    def set_mode(self, mode_name: str) -> None: ...
    def get_current_mode(self) -> str: ...
    def quit(self) -> None: ... 