from typing import Protocol, Optional

class IFileService(Protocol):
    """ファイルサービスのインターフェース"""
    
    def load_file(self, filepath: str) -> bool: ...
    def save_file(self, filepath: Optional[str] = None) -> bool: ...
    def set_encoding(self, encoding: str) -> bool: ...
    def get_file_info(self) -> dict: ...
    def is_modified(self) -> bool: ...
    def mark_modified(self) -> None: ... 