from typing import Protocol, Optional, Any

class INotificationService(Protocol):
    """通知サービスのインターフェース"""
    
    def add(self, message: str, level=None, duration: float = 3.0, metadata: Optional[dict] = None) -> None: ...
    def add_info(self, message: str, duration: float = 3.0) -> None: ...
    def add_success(self, message: str, duration: float = 3.0) -> None: ...
    def add_warning(self, message: str, duration: float = 4.0) -> None: ...
    def add_error(self, message: str, duration: float = 5.0) -> None: ...
    def clear(self) -> None: ... 